/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package techshop_sale;


import java.sql.*;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.DriverManager;

import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author Zarin Hossain
 */
public class Techshop extends javax.swing.JFrame {

    /**
     * Creates new form Techshop
     */
    public Techshop() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCustomerId = new javax.swing.JTextField();
        txtProductNames = new javax.swing.JTextField();
        txtProductPrices = new javax.swing.JTextField();
        insertButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        viewButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtCustName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtCustPhone = new javax.swing.JTextField();
        clearButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        computerCategoryList = new javax.swing.JList<>();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        mobileCategoryList = new javax.swing.JList<>();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        generalCategoryList = new javax.swing.JList<>();
        jLabel10 = new javax.swing.JLabel();
        saleDate = new org.jdesktop.swingx.JXDatePicker();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResult = new javax.swing.JTextArea();
        refreshButton = new javax.swing.JButton();
        searchButton = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 204));

        jLabel1.setBackground(new java.awt.Color(153, 153, 255));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Techshop");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(30, 30, 30))
        );

        jPanel2.setBackground(new java.awt.Color(51, 153, 255));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Customer ID: ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Product Names: ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Product Prices: ");

        jLabel5.setBackground(new java.awt.Color(51, 51, 255));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Computer Product Catagory: ");

        txtCustomerId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustomerIdActionPerformed(evt);
            }
        });

        txtProductNames.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProductNamesActionPerformed(evt);
            }
        });

        insertButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        insertButton.setText("INSERT");
        insertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertButtonActionPerformed(evt);
            }
        });

        updateButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        updateButton.setText("UPDATE");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        deleteButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        deleteButton.setText("DELETE");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        viewButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        viewButton.setText("View Details");
        viewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewButtonActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Customer Name: ");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Customer Phone Number: ");

        clearButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        clearButton.setText("Clear Details");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        computerCategoryList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Processor", "Ram", "Monitor", "Mouse", "Hard disk", "Other" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(computerCategoryList);

        jLabel8.setBackground(new java.awt.Color(51, 51, 255));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Mobile Product Catagory: ");

        mobileCategoryList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Samsung", "Apple", "Xiomi", "Vivo", "Oppo", "Walton", "HTC", "Nokia", "Symphony", "Redmi", "Motorola", "Other" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(mobileCategoryList);

        jLabel9.setBackground(new java.awt.Color(51, 51, 255));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("General Product Catagory: ");

        generalCategoryList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Earphones", "Socket", "Multimeter", "Switch", "Wires", "Fan", "Light", "Regulator", "Other" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(generalCategoryList);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Sale Date:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(insertButton)
                        .addGap(42, 42, 42)
                        .addComponent(updateButton)
                        .addGap(37, 37, 37)
                        .addComponent(deleteButton))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel10))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(saleDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCustPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCustName, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtCustomerId, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 156, Short.MAX_VALUE)
                                .addComponent(viewButton))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtProductNames, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                                    .addComponent(txtProductPrices))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(clearButton)))
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(109, 109, 109)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel8)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCustomerId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewButton))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtProductNames, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProductPrices, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearButton)
                    .addComponent(jLabel4))
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel6))
                    .addComponent(txtCustName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtCustPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(saleDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(insertButton)
                    .addComponent(updateButton)
                    .addComponent(deleteButton))
                .addGap(18, 18, 18)
                .addComponent(backButton)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Set Data", jPanel2);

        jPanel3.setBackground(new java.awt.Color(51, 102, 255));

        txtResult.setEditable(false);
        txtResult.setBackground(new java.awt.Color(153, 204, 255));
        txtResult.setColumns(20);
        txtResult.setRows(5);
        txtResult.setText("Click Refresh to see the list.\n");
        txtResult.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane1.setViewportView(txtResult);

        refreshButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        refreshButton.setText("Refresh");
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });

        searchButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(refreshButton)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(searchButton)))
                        .addGap(0, 217, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchButton)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(refreshButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("View Data", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCustomerIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustomerIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustomerIdActionPerformed

    private void txtProductNamesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProductNamesActionPerformed
        // TODO add your handling code here::
    }//GEN-LAST:event_txtProductNamesActionPerformed

    private void insertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertButtonActionPerformed
        String productsComputer=new String();
        for(int i=0;i<computerCategoryList.getSelectedValuesList().size();i++)
        {
            if(computerCategoryList.getSelectedValuesList().size()-1==i)
                productsComputer+=((String)computerCategoryList.getSelectedValuesList().get(i));
            else
                productsComputer+=((String)computerCategoryList.getSelectedValuesList().get(i)+",");
        }
        String productsMobile=new String();
        for(int i=0;i<mobileCategoryList.getSelectedValuesList().size();i++)
        {
            if(mobileCategoryList.getSelectedValuesList().size()-1==i)
                productsMobile+=((String)mobileCategoryList.getSelectedValuesList().get(i));
            else
                productsMobile+=((String)mobileCategoryList.getSelectedValuesList().get(i)+",");
        }
        String productsGeneral=new String();
        for(int i=0;i<generalCategoryList.getSelectedValuesList().size();i++)
        {
            if(generalCategoryList.getSelectedValuesList().size()-1==i)
                productsGeneral+=((String)generalCategoryList.getSelectedValuesList().get(i));
            else
                productsGeneral+=((String)generalCategoryList.getSelectedValuesList().get(i)+",");
        }

        if(saleDate.getDate()==null)
        {
            JOptionPane.showMessageDialog(null, "Please Select a date");
            return; 
        }
        String sale_date=new SimpleDateFormat("YYYY/MM/dd").format(saleDate.getDate());
        
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/techshop_sale", "root", "");
            Statement stmt = (Statement) con.createStatement();
            String query = "insert into techshop_sale (customer_id, customer_name, customer_phone, product_names, product_prices, category_computer, category_mobile, category_general, sale_date) values ('"+txtCustomerId.getText()+"', '"+txtCustName.getText()+"', '"+txtCustPhone.getText()+"', '"+txtProductNames.getText()+"', '"+txtProductPrices.getText()+"', '"+productsComputer+"', '"+productsMobile+"', '"+productsGeneral+"', '"+sale_date+"')";
            stmt.executeUpdate(query);
            JOptionPane.showMessageDialog(null, "Data successfullly inserted");
                       
        }catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Error"+ e);
        }
    }//GEN-LAST:event_insertButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        String productsComputer=new String();
        for(int i=0;i<computerCategoryList.getSelectedValuesList().size();i++)
        {
            if(computerCategoryList.getSelectedValuesList().size()-1==i)
                productsComputer+=((String)computerCategoryList.getSelectedValuesList().get(i));
            else
                productsComputer+=((String)computerCategoryList.getSelectedValuesList().get(i)+",");
        }
        String productsMobile=new String();
        for(int i=0;i<mobileCategoryList.getSelectedValuesList().size();i++)
        {
            if(mobileCategoryList.getSelectedValuesList().size()-1==i)
                productsMobile+=((String)mobileCategoryList.getSelectedValuesList().get(i));
            else
                productsMobile+=((String)mobileCategoryList.getSelectedValuesList().get(i)+",");
        }
        String productsGeneral=new String();
        for(int i=0;i<generalCategoryList.getSelectedValuesList().size();i++)
        {
            if(generalCategoryList.getSelectedValuesList().size()-1==i)
                productsGeneral+=((String)generalCategoryList.getSelectedValuesList().get(i));
            else
                productsGeneral+=((String)generalCategoryList.getSelectedValuesList().get(i)+",");
        }
        try {
            if(saleDate.getDate()==null)
            {
                JOptionPane.showMessageDialog(null, "Please Select a date");
                return; 
            }
            String sale_date=new SimpleDateFormat("YYYY/MM/dd").format(saleDate.getDate());
            Class.forName("com.mysql.jdbc.Driver");           
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/techshop_sale", "root", "");
            Statement stmt = (Statement) con.createStatement();
            String query = "update techshop_sale set product_names= '"+txtProductNames.getText()+"',product_prices= '"+txtProductPrices.getText()+"',category_computer= '"+productsComputer+"',category_mobile= '"+productsMobile+"',category_general= '"+productsGeneral+"',customer_name= '"+txtCustName.getText()+"',customer_phone= '"+txtCustPhone.getText()+"',sale_date= '"+sale_date+"' where customer_id= '"+txtCustomerId.getText()+"';";
            stmt.executeUpdate(query);
            JOptionPane.showMessageDialog(null, "Data updated successfully");
                       
        }catch(Exception ex) {
            JOptionPane.showMessageDialog(null, "Error"+ ex);
        }
    }//GEN-LAST:event_updateButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        try {
            Class.forName("com.mysql.jdbc.Driver");           
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/techshop_sale", "root", "");
            Statement stmt = (Statement) con.createStatement();
            String query = "delete from techshop_sale where customer_id= '"+txtCustomerId.getText()+"'  ";
            stmt.executeUpdate(query);
            JOptionPane.showMessageDialog(null, "Data deleted successfullly");
                       
        }catch(Exception ex) {
            JOptionPane.showMessageDialog(null, "Error"+ ex);
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void viewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewButtonActionPerformed
        try {
            if("".equals(txtCustomerId.getText()))
            {
                JOptionPane.showMessageDialog(null, "Please enter a customer id to view.");
                return; 
            }
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/techshop_sale", "root", "");
            String query = "select * from techshop_sale where customer_id ='"+txtCustomerId.getText()+"'";
            PreparedStatement statement = con.prepareStatement(query);
            
            ResultSet set = statement.executeQuery();
            if(!set.next())
            {
                JOptionPane.showMessageDialog(null, "There is no record in customer id = "+txtCustomerId.getText()+".\nPlease enter proper customer id.");
                return; 
            }
            else{
                txtProductNames.setText(set.getString("product_names"));
                txtProductPrices.setText(set.getString("product_prices"));
                txtCustName.setText(set.getString("customer_name"));
                txtCustPhone.setText(set.getString("customer_phone"));
                String saleDateStr=set.getString("sale_date");
                saleDate.setDate(new SimpleDateFormat("yyyy-MM-dd").parse(saleDateStr));
                
                String categoriesComputer[]=set.getString("category_computer").split(",");
                int []computerIndexes=new int[categoriesComputer.length];
                for(int j=0;j<categoriesComputer.length;j++)
                    for(int i=0;i<computerCategoryList.getModel().getSize();i++)            
                        if(computerCategoryList.getModel().getElementAt(i).equals(categoriesComputer[j]))
                            computerIndexes[j]=i;
                        else if((categoriesComputer[j]).equals(""))
                                    computerIndexes[j]=-1;
                computerCategoryList.setSelectedIndices(computerIndexes);
                String categoriesMobile[]=set.getString("category_mobile").split(",");
                int []mobileIndexes=new int[categoriesMobile.length];
                for(int j=0;j<categoriesMobile.length;j++)
                    for(int i=0;i<mobileCategoryList.getModel().getSize();i++)            
                        if(mobileCategoryList.getModel().getElementAt(i).equals(categoriesMobile[j]))// "String".equals("string") = "String=="string"
                            mobileIndexes[j]=i;
                        else if((categoriesMobile[j]).equals(""))
                                    mobileIndexes[j]=-1;
                mobileCategoryList.setSelectedIndices(mobileIndexes);
                String categoriesGeneral[]=set.getString("category_general").split(",");
                int []generalIndexes=new int[categoriesGeneral.length];
                for(int j=0;j<categoriesGeneral.length;j++)
                    for(int i=0;i<generalCategoryList.getModel().getSize();i++)            
                        if(generalCategoryList.getModel().getElementAt(i).equals(categoriesGeneral[j]))
                            generalIndexes[j]=i;
                        else if((categoriesGeneral[j]).equals(""))
                                    generalIndexes[j]=-1;
                generalCategoryList.setSelectedIndices(generalIndexes);
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Error"+ ex);
        }

    }//GEN-LAST:event_viewButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        // TODO add your handling code here:
        txtProductNames.setText(null);
        txtProductPrices.setText(null);
        txtCustomerId.setText(null);
        txtCustName.setText(null);
        txtCustPhone.setText(null);
        computerCategoryList.clearSelection();
        mobileCategoryList.clearSelection();
        generalCategoryList.clearSelection();
        saleDate.setDate(null);
    }//GEN-LAST:event_clearButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        new Main().setVisible(true);

    }//GEN-LAST:event_backButtonActionPerformed

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        // TODO add your handling code here:
        String result=new String();
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/techshop_sale", "root", "");
            String query = "select * from techshop_sale order by customer_id;";
            PreparedStatement statement = con.prepareStatement(query);
            
            ResultSet set = statement.executeQuery();
            if(!set.next())
            {
                JOptionPane.showMessageDialog(null, "There is no record in Database.\nPlease enter at least one record.");
                return; 
            }
            else{
                set.previous();
                while(set.next()){
                    result+="Customer ID: "+(set.getString("customer_id"))+"\n";
                    result+="Customer Name: "+(set.getString("customer_name"))+"\n";
                    result+="Customer Phone: "+(set.getString("customer_phone"))+"\n";
                    String productsUpper[]=(set.getString("product_names")).split(";");
                    String products[][]=new String[productsUpper.length][];
                    String pricesUpper[]=(set.getString("product_prices")).split(";");
                    String prices[][]=new String[productsUpper.length][];
                    String categories[];
                    for(int i=0;i<productsUpper.length;i++)
                    {
                        products[i]=productsUpper[i].split(",");
                        prices[i]=pricesUpper[i].split(",");
                    }
                    for(int i=0;i<products.length;i++)
                    {
                        if(i==0)
                        {
                            categories=set.getString("category_computer").split(",");
                            result+="\nComputer Categories:\n";
                        }
                        else if(i==1)
                        {
                            categories=set.getString("category_mobile").split(",");
                            result+="\nMobile Categories:\n";
                        }
                        else
                        {
                            categories=set.getString("category_general").split(",");
                            result+="\nGeneral Categories:\n";
                        }
                        for(int j=0;j<products[i].length;j++)
                        {
                            if("".equals(products[i][j]))
                                continue;
                            result+="\tProduct Name: "+products[i][j]+"\n";
                            result+="\tProduct Price: "+prices[i][j]+" Taka\n";
                            result+="\tCategory: "+categories[j]+"\n\n";
                        }
                    }
                    result+="Sale Date: "+set.getString("sale_date")+"\n";
                    result+="\n\n";
                }
            }
            txtResult.setText(result);
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Error"+ ex);
        }
    }//GEN-LAST:event_refreshButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
        String result=new String();
        try {
            if("".equals(txtSearch.getText()))
            {
                JOptionPane.showMessageDialog(null, "Please enter a customer id to view.");
                return; 
            }
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/techshop_sale", "root", "");
            String query = "select * from techshop_sale where customer_id='"+txtSearch.getText()+"';";
            PreparedStatement statement = con.prepareStatement(query);
            
            ResultSet set = statement.executeQuery();
            if(!set.next())
            {
                JOptionPane.showMessageDialog(null, "There is no record in customer id = "+txtSearch.getText()+".\nPlease enter proper customer id.");
                return; 
            }
            else{
                result+="Customer ID: "+(set.getString("customer_id"))+"\n";
                result+="Customer Name: "+(set.getString("customer_name"))+"\n";
                result+="Customer Phone: "+(set.getString("customer_phone"))+"\n";
                String productsUpper[]=(set.getString("product_names")).split(";");
                String products[][]=new String[productsUpper.length][];
                String pricesUpper[]=(set.getString("product_prices")).split(";");
                String prices[][]=new String[productsUpper.length][];
                String categories[];
                for(int i=0;i<productsUpper.length;i++)
                {
                    products[i]=productsUpper[i].split(",");
                    prices[i]=pricesUpper[i].split(",");
                }
                for(int i=0;i<products.length;i++)
                {
                    if(i==0)
                    {
                        categories=set.getString("category_computer").split(",");
                        result+="\nComputer Categories:\n";
                    }
                    else if(i==1)
                    {
                        categories=set.getString("category_mobile").split(",");
                        result+="\nMobile Categories:\n";
                    }
                    else
                    {
                        categories=set.getString("category_general").split(",");
                        result+="\nGeneral Categories:\n";
                    }
                    for(int j=0;j<products[i].length;j++)
                    {
                        if("".equals(products[i][j]))
                            continue;
                        result+="\tProduct Name: "+products[i][j]+"\n";
                        result+="\tProduct Price: "+prices[i][j]+" Taka\n";
                        result+="\tCategory: "+categories[j]+"\n\n";
                    }
                }
                result+="Sale Date: "+set.getString("sale_date")+"\n";
                result+="\n\n";
            }
            txtResult.setText(result);
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Error"+ ex);
        }
    }//GEN-LAST:event_searchButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Techshop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Techshop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Techshop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Techshop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Techshop().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JList<String> computerCategoryList;
    private javax.swing.JButton deleteButton;
    private javax.swing.JList<String> generalCategoryList;
    private javax.swing.JButton insertButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JList<String> mobileCategoryList;
    private javax.swing.JButton refreshButton;
    private org.jdesktop.swingx.JXDatePicker saleDate;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField txtCustName;
    private javax.swing.JTextField txtCustPhone;
    private javax.swing.JTextField txtCustomerId;
    private javax.swing.JTextField txtProductNames;
    private javax.swing.JTextField txtProductPrices;
    private javax.swing.JTextArea txtResult;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JButton updateButton;
    private javax.swing.JButton viewButton;
    // End of variables declaration//GEN-END:variables
}
